-- 添加分站额外域名字段
ALTER TABLE `pre_site` ADD COLUMN `domain3` VARCHAR(255) NULL DEFAULT NULL AFTER `domain2`;
ALTER TABLE `pre_site` ADD COLUMN `domain4` VARCHAR(255) NULL DEFAULT NULL AFTER `domain3`;
ALTER TABLE `pre_site` ADD COLUMN `domain5` VARCHAR(255) NULL DEFAULT NULL AFTER `domain4`;
ALTER TABLE `pre_site` ADD COLUMN `domain6` VARCHAR(255) NULL DEFAULT NULL AFTER `domain5`;